### ISSUE TITLE
View are not updating

### ISSUE THREAD

**Issue by ak0der1** [DeBos99/ytviewer#16]
I am trying it with luminati's residential proxies. but still views are not being counted in real time even. Can you suggest me any change?

**Comment by ayeshakhan2118** [comment]
can uh help me man ?

**Comment by ayeshakhan2118** [comment]
i have this problem  python2 main.py -u https://www.youtube.com/watch?v=5D9Ri_9EoSE -d 10 -dr firefox 
100 proxies successfully loaded!
182.52.74.76:34084
Traceback (most recent call last):
  File "main.py", line 68, in bot
    driver=webdriver.Firefox(firefox_profile=firefox_profile,options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

**Comment by DeBos99** [comment]
Please use template when reporting a bug.
