### ISSUE TITLE
[BUG] SSLError

### ISSUE THREAD

**Issue by xtacyyy** [DeBos99/ytviewer#30]
**Description**
Just re-installed the project, tried running it for the first time and it gives a bad handshake error. 

**Command**
python main.py -u https://www.youtube.com/watch?v=4Lh7VyI1rEc -d 45 -t 3

**Logs**
Traceback (most recent call last):
  File "main.py", line 67, in bot
    proxies.extend(get_proxies())
  File "main.py", line 57, in get_proxies
    proxies=re.findall(re.compile('<td>([\d.]+)</td>'),str(requests.get('https://www.sslproxies.org/').content))
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

**Software**
OS: Kali Linux
Python version:  2.7.16
WebDriver: Chrome

**Comment by DeBos99** [comment]
Did you run program as normal user? Root is not supported at this moment.

**Comment by xtacyyy** [comment]
I tried doing that, still gives the same input.

**Comment by DeBos99** [comment]
Try running `sudo pip install -U requests[security]` and tell me if that helps.

**Comment by DeBos99** [comment]
I made minor update to the bot. Tell me if the issue still persists.

**Comment by xtacyyy** [comment]
I just figured out that the proxy site the bot uses is blocked in my country. So the bot could not access the proxy list. However, I started a vpn connection using openvpn and now the bot can load the proxies but however, it gives the following code :

Traceback (most recent call last):
  File "main.py", line 109, in bot
    driver.get(url)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Reached error page: about:neterror?e=proxyConnectFailure&u=https%3A//www.youtube.com/watch%3Fv%3D4Lh7VyI1rEc&c=UTF-8&f=regular&d=Firefox%20is%20configured%20to%20use%20a%20proxy%20server%20that%20is%20refusing%20connections.

**Comment by DeBos99** [comment]
This error says that driver can't connect to proxy. I have to fix error handling for firefox.

**Comment by DeBos99** [comment]
Bug should be fixed.
