### ISSUE TITLE
[BUG] driver.get(url)

### ISSUE THREAD

**Issue by marko900** [DeBos99/ytviewer#31]
Bot open Firefox and suddenly it close because this error appears.

**Command**
python main.py -t 1 -u lista.txt -dr firefox

**Logs**

Traceback (most recent call last):
  File "/home/pi/ytviewer/main.py", line 108, in bot
    driver.get(url)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Reached error page: about:neterror?e=proxyConnectFailure&u=https%3A//www.youtube.com/watch%3Fv%MY VIDEO&c=UTF-8&f=regular&d=Firefox%20is%20configured%20to%20use%20a%20proxy%20server%20that%20is%20refusing%20connections.

**Software**
OS: Rasppbian
Python version: Python 2.7.13
WebDriver: Firefox

**Comment by DeBos99** [comment]
I'm aware of this issue and I'm working on some bug fixes now. Please use `chromedriver` until the issue will be fixed.

**Comment by DeBos99** [comment]
Bug should be fixed.
