### ISSUE TITLE
[BUG] After starting

### ISSUE THREAD

**Issue by BopaxDev** [DeBos99/ytviewer#44]
I have executed the program:
python main.py --url https://www.youtube.com/watch?v=xxxxxxxxxxxx --driver firefox

it doesn't show me any strings, i have tried it with other option like chrome for driver but i have the same issue.

(I have censured the youtube link with xxxx)

**Comment by DeBos99** [comment]
Add `--debug` option and see if there are any errors.

**Comment by BopaxDev** [comment]
It show me

[INFO] 1068 proxies successfully loaded!
[INFO][1] Connecting to 117.242.147.85:56339
[INFO][1] Setting user agent to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2637.59 Safari/537.36
[WARNING][1] WebDriverException
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 106, in bot
    driver=webdriver.Chrome(options=chrome_options,executable_path=executable_path)
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

[INFO] Exitting with exit code 1

I have set chromedriver in PATH and also in the main.py's directory.

The command typed:
python main.py -u https://www.youtube.com/watch?v=xxx -D chrome --debug --thread 1

**Comment by BopaxDev** [comment]
fixed, i have studied the main file and i have seen that executable dir wasn't the main.py's directory but was 'C:\Users\x\AppData\Roaming\DeBos\drivers' now i have imported in this dir 'chromedriver.exe'

Thanks for all

**Comment by DeBos99** [comment]
The first error means that something went wrong during installation, so `chromedriver.exe` wasn't in `C:\Users\x\AppData\Roaming\DeBos\drivers` directory.
Second 'error' is just warning. `--debug` converts all warnings to errors, so you can remove `--debug` and everything should work fine.
