### ISSUE TITLE
Error when trying to load

### ISSUE THREAD

**Issue by dropitlikecross** [DeBos99/ytviewer#47]
```
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    try:INSTALLED
NameError: name 'INSTALLED' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 88, in <module>
  File "main.py", line 19, in log
    if args.debug:
NameError: name 'args' is not defined
[INFO] Exitting with exit code 1
instabot@instabot:~/ytviewer$ 
```

**Comment by dropitlikecross** [comment]
Sorry I didnt see the requirements.txt
