### ISSUE TITLE
[BUG][INFO] Exitting with exit code 1

### ISSUE THREAD

**Issue by martincol21** [DeBos99/ytviewer#68]
Not working on Raspberry pi 3b

**Command**
sudo python3.7 main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H -D firefox

**Logs**
pi@raspberrypi:~/ytviewer $ sudo python3.7 main.py -u https://www.youtube.com/watch?v=cElhIDdGz7M -d -H -D firefox
[INFO] Bot is not installed.
[INFO] Starting installation.
[INFO] Detected 7lbit architecture
[INFO] Starting driver installation.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: wget in /root/.local/lib/python3.7/site-packages (3.2)
Select browser for webdriver:
[INFO] Downloading webdriver from: https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux7l.tar.gz
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    from psutil import Process,NoSuchProcess
ModuleNotFoundError: No module named 'psutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 50, in <module>
    try:INSTALLED
NameError: name 'INSTALLED' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 87, in <module>
  File "<string>", line 60, in install
  File "/root/.local/lib/python3.7/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[INFO] Exitting with exit code 1

**Software**
OSl Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
Python version: 3.72

**Comment by DeBos99** [comment]
Only 32-bit and 64-bit machines are technically supported. If you would add me on Discord (DeBos#3292) I could try to change it.
